"""tables initiales : strategies, signals, paper_positions, paper_trades

Revision ID: 5d0c3c19d403
Revises: 
Create Date: 2026-08-23 01:28:03.974432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0c3c19d403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('risk_reward', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('signal_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('discord_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('BUY', 'SELL')", name='ck_signals_action'),
    sa.CheckConstraint("status IN ('RECEIVED', 'VALIDATED', 'SENT', 'REJECTED', 'DUPLICATE', 'ERROR')", name='ck_signals_status'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_uid'), 'signals', ['signal_uid'], unique=True)
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_index('ix_signals_strategy_timestamp', 'signals', ['strategy_id', 'signal_timestamp'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_timestamp', 'signals', ['symbol', 'signal_timestamp'], unique=False)
    op.create_index(op.f('ix_signals_timeframe'), 'signals', ['timeframe'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_r', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name='ck_paper_positions_status'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_signal_id'), 'paper_positions', ['signal_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_position_id', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=4), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("exit_reason IN ('TP', 'SL')", name='ck_paper_trades_exit_reason'),
    sa.ForeignKeyConstraint(['paper_position_id'], ['paper_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_paper_position_id'), 'paper_trades', ['paper_position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_paper_position_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_paper_positions_signal_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_signals_timeframe'), table_name='signals')
    op.drop_index('ix_signals_symbol_timestamp', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_strategy_timestamp', table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_uid'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('strategies')
    # ### end Alembic commands ###
